### ISSUE TITLE
Does this work on version beyond "0.9.8" of pysigma?

### ISSUE THREAD

**Issue by iamtimroberts** [7RedViolin/pySigma-backend-cortexxdr#6]
Latest pysigma is 0.10.6 and this causes incompatibility issues with the Cortex XDR plugin.

**Comment by 7RedViolin** [comment]
Thanks for the heads up, @iamtimroberts ! Version 0.1.2 of this plugin is now available and should resolve that issue. From my testing, it looked like the version dependencies listed in pyproject.toml were the only items needed to be changed for this plugin to work with pySigma 0.10.X but let me know if that's not the case and you still run into issues.
