### ISSUE TITLE
Sigma Rule Issue.  Any idea to fix this?

### ISSUE THREAD

**Issue by ndeshappriya** [7RedViolin/pySigma-backend-cortexxdr#8]
Sigma convert -t cortex_xdr proc_creation_win_office_onenote_susp_child_processes.yml
Parsing Sigma rules  [####################################]  100%
Error while conversion: Invalid SigmaDetectionItem field name encountered: OriginalFileName. This pipeline only supports the following fields:
{CommandLine}, {Company}, {CurrentDirectory}, {DestinationIp}, {DestinationPort}, {Details}, {Image}, {ImageLoaded}, {IntegrityLevel}, {ParentCommandLine}, {ParentImage}, {ParentProcessId}, {ProcessId}, {Product}, {Protocol}, {SourceFilename}, {SourceIp}, {SourcePort}, {TargetFilename}, {TargetObject}, {User}, {dst_ip}, {dst_port}, {md5}, {sha256}, {src_ip}, {src_port}

**Comment by 7RedViolin** [comment]
Hi @ndeshappriya ! That documentation needs to be updated as `OriginalFileName` is currently not supported by the Cortex XDR pipeline. I'm not aware of a native Cortex XDR field name equivalent but if you have a recommendation, let me know so I can test it and potentially update this translator!
